### ISSUE TITLE
open connection failed.

### ISSUE THREAD

**Issue by zxuewu** [manticoresoftware/go-sdk#23]
I try to connect to manticore search server by open() function, and got error message "Wrong version num received: 2600468480". I do not know what happend. I connect server with "ip/port", and the server is running.

**Comment by sanikolaev** [comment]
It works fine here https://play.manticoresearch.com/go-sdk/ 
Please make sure you are connecting to a proper port (9312 by default)

**Comment by zxuewu** [comment]
The server port has been changed (not 9312 by default). I try to debug this problem, this error happend where send handshake message ( 'handshake.putUint(cphinxClientVersion)' ), and when read the buf ( 'ver := buf.getDword()' ), ver is 2600468480 not equal to cphinxSearchdProto, and throw the error message "Wrong version num received: 2600468480" .

**Comment by zxuewu** [comment]
Sorry about this. I change the port to default 9312, and it worked. I made this mistake, because I use mysql client with another port, and connect succeed.
